### ISSUE TITLE
Doe not work with sprockets

### ISSUE THREAD

**Issue by MartinBober** [katgironpe/textile_editor_helper#9]
Since Rails 4, the asset pipeline/sprockets does not offer "non-digested" asset file names any more. However, the textile_editor_helper still relies on those "non-digested" asset file names and fails in my production environment.

See: https://github.com/rails/sprockets-rails/issues/49

**Comment by kathgironpe** [comment]
@MartinBober You have to add the files to the list. Normally, we use regular expressions. I am not sure why it should not work for you.

**Comment by kathgironpe** [comment]
@MartinBober This is what I am talking about: 

``` ruby
    config.assets.precompile = [/^(.+\/)?[^_][.a-zA-Z\d_-]*\.(js|coffee|png|gif
                                                              |jpg|swf|css|scss|sass|
                                                              |erb|html
                                                              |ico|woff|svg
                                                              |eot|ttf)+$/]
```

If you have this and it is still not working, it may be a valid problem. This gem is simple: it just copies some files to asset directories, and provides some helpers. 

Let me know if it works for you.
